extends: default

rules:
  brackets: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines: disable
  indentation: disable
  line-length: disable
  trailing-spaces: disable
  truthy:
    allowed-values: ['true', 'false', 'on']