name: Host Us
description: Join Cloud Native Linz as a host and help us organize the next meetup.
title: "[Hosting Request]: "
labels: [ "hosting-request" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in hosting one of the next Cloud Native Linz meetups! We're excited to get to know you and your company.
  - type: input
    id: name
    attributes:
      label: What's your name?
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach out to you?
    validations:
      required: true
  - type: input
    id: company
    attributes:
      label: Company Name
    validations:
      required: true
  - type: textarea
    id: additionalinfo
    attributes:
      label: additional Information 
      description: Is there anything else you would like to share with us?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md).
      options:
        - label: I agree to follow this meetups's Code of Conduct
          required: true
